[project]
name = "NodeJackPot"
version = "0.1.0"
src = "contracts"
dot_vy_imports = ["lib"]

[dependencies]
snekmate = { path = "lib/snekmate" }

[networks.pyevm]
is_zksync = false

[networks.pyevm.contracts.mock_vrf_coordinator]
path = "contracts/mocks/mock_vrf_coordinator.vy"

[networks.pyevm.extra_data]
subscription_id = 0
gas_lane = "0x787d74caea10b2b357790d5b5247c2f63d1d91572a9846f780606e4d953677ae"
callback_gas_limit = 500000
entrance_fee = 1000000000000000
interval = 30

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
chain_id = 31337
default_account_name = 'anvil1'

[networks.anvil.contracts.mock_vrf_coordinator]
path = "contracts/mocks/mock_vrf_coordinator.vy"

[networks.anvil.extra_data]
subscription_id = 0
gas_lane = "0x787d74caea10b2b357790d5b5247c2f63d1d91572a9846f780606e4d953677ae"
callback_gas_limit = 500000
entrance_fee = 1000000000000000
interval = 30